# ----
# Site

title: BlueMail Help
url: "https://bluemail.blue"
baseurl:
google_analytics_key:
disqus_shortname:
newsletter_action:
excerpt_separator: ""

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Help Center for BlueMail
author:
  name:
  email:
  twitter: # twitter username without the @ symbol
social:
  name: Base Template
  links:
    - https://github.com/CloudCannon/base-jekyll-template

# -----
# Build

languages: ["en", "de"]
default_lang: "en"
exclude_from_localization: ["javascript", "images", "css", "scss"]
parallel_localization: true

permalink: /:title/

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-archives

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

collections:
  - _mainview
  # sets:



jekyll-archives:
  enabled: ['categories']

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      type: "posts"
    values:
      layout: "post"
      comments: true
  -
    scope:
      type: "sets"
    values:
      _hide_content: true
  -
    scope:
      path: "index.html"
    values:
      body_class: "show_hero_search"
# -----------
# CloudCannon

social_icons:
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - Email
  - RSS

types:
  - Document
  - Video
  - post

_comments:


_editable_regions:
  image:
    url_src: true


searchplaceholder:
  en: Search
  de: Suche

helpcenter:
  en: Help Center
  de: Hilfezentrum

everythingblue:
  en: Everything you need to know about making BlueMail work for you
  de: Alles, was Sie wissen müssen, um BlueMail zu machen, arbeiten für Sie